"Abolish teh the
"Abolish itn int
"Abolish seperate separate
"Abolish taht that
"Abolish tath that
"Abolish waht what
"Abolish yei{ld,dl} yield
"Abolish reciever receiver
"Abolish flaot float
"Abolish nul null
"Abolish peice piece
"Abolish dispathc dispatch
"Abolish functoin function
"Abolish swithc switch
"Abolish siwtch switch
"Abolish siwthc switch
"Abolish ietm item
